export const GET_ALL_BREEDS = "GET_ALL_BREEDS";
export const GET_BREED_DETAILS = "GET_BREED_DETAILS";
export const GET_BREEDS_WITH_PAGINATE = "GET_BREEDS_WITH_PAGINATE";
export const GET_BREEDS_BY_NAME = "GET_BREEDS_BY_NAME";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const RESET_BREEDS = "RESET_BREEDS";
export const SET_FILTER_DATA = "SET_FILTER_DATA";

export const SHOW_MODAL_TEMPERAMENTS = "SHOW_MODAL_TEMPERAMENTS";
export const CLOSE_MODAL_TEMPERAMENTS = "CLOSE_MODAL_TEMPERAMENTS";
export const SEARCH_TEMPERAMENTS_MODAL = "SEARCH_TEMPERAMENTS_MODAL";
export const ADD_TEMPERAMENT_TO_FILTERS = "ADD_TEMPERAMENT_TO_FILTERS";
export const REMOVE_TEMPERAMENT_FROM_FILTERS = "REMOVE_TEMPERAMENT_FROM_FILTERS";

export const SHOW_HOME = "SHOW_HOME";
export const RESET_HOME = "RESET_HOME";
export const SHOW_LOADING = "SHOW_LOADING";
export const CHANGE_THEME = "CHANGE_THEME";