export const GET_ALL_BREEDS = "GET_ALL_BREEDS";
export const GET_BREED_DETAILS = "GET_BREED_DETAILS";
export const GET_BREEDS_WITH_PAGINATE = "GET_BREEDS_WITH_PAGINATE";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";

export const SHOW_HOME = "SHOW_HOME";
export const RESET_HOME = "RESET_HOME";
export const SHOW_LOADING = "SHOW_LOADING";