export const GET_ALL_BREEDS = "GET_ALL_BREEDS";
export const GET_BREED_DETAILS = "GET_BREED_DETAILS";
export const GET_BREEDS_WITH_PAGINATE = "GET_BREEDS_WITH_PAGINATE";
export const GET_BREEDS_BY_NAME = "GET_BREEDS_BY_NAME";
export const GET_TEMPERAMENTS = "GET_TEMPERAMENTS";
export const GET_BREEDS_WITH_PAGINATE_LOCAL = "GET_BREEDS_WITH_PAGINATE_LOCAL";
export const BREEDS_NOT_FOUND = 'Breed not found';
export const RESET_BREEDS = "RESET_BREEDS";
export const SET_FILTER_DATA = "SET_FILTER_DATA";
export const SET_PAGE = "SET_PAGE";

export const SHOW_MODAL_TEMPERAMENTS = "SHOW_MODAL_TEMPERAMENTS";
export const CLOSE_MODAL_TEMPERAMENTS = "CLOSE_MODAL_TEMPERAMENTS";
export const SEARCH_TEMPERAMENTS_MODAL = "SEARCH_TEMPERAMENTS_MODAL";
export const ADD_TEMPERAMENT_TO_FILTERS = "ADD_TEMPERAMENT_TO_FILTERS";
export const REMOVE_TEMPERAMENT_FROM_FILTERS = "REMOVE_TEMPERAMENT_FROM_FILTERS";

export const INITIALIZE_NEW_DOG = 'INITIALIZE_NEW_DOG';
export const VALIDATE_PROPERTY_DOG = 'VALIDATE_PROPERTY_DOG';
export const VALIDATING = 'VALIDATING';
export const CHECK_IF_NAME_IS_AVALAIBLE = 'CHECK_IF_NAME_IS_AVALAIBLE';
export const CHANGE_FORM_CREATE_SECTION = 'CHANGE_FORM_CREATE_SECTION';
export const SET_BACK_PAGE_ANIMATION = 'SET_BACK_PAGE_ANIMATION';
export const SET_NEXT_PAGE_ANIMATION = 'SET_NEXT_PAGE_ANIMATION';
export const CHANGE_TEMPERAMENTS_OF_NEW_DOG = 'CHANGE_TEMPERAMENTS_OF_NEW_DOG';
export const SHOW_MODAL_CREATE_TEMPERAMENT = 'SHOW_MODAL_CREATE_TEMPERAMENT';
export const CLOSE_MODAL_CREATE_TEMPERAMENT = 'CLOSE_MODAL_CREATE_TEMPERAMENT';
export const CHANGE_SIZE_OF_NEW_DOG = 'CHANGE_SIZE_OF_NEW_DOG';

export const SHOW_HOME = "SHOW_HOME";
export const RESET_HOME = "RESET_HOME";
export const SHOW_LOADING = "SHOW_LOADING";
export const CHANGE_THEME = "CHANGE_THEME";